In [53]:
#importing the dependecies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
#loading the dataset into the workspace
data = pd.read_csv('poddf.csv')
data.head()

index                            Name Rating_Volume   Rating       Genre  \
0      0                       Fresh Air         10188  4.46133        Arts   
1      1                        The Moth         10154  4.69982  Performing   
2      2                   99% Invisible         12303   4.8693      Design   
3      3  iFanboy.com Comic Book Podcast          1335  4.79551      Visual   
4      4               Myths and Legends         11128  4.88282  Literature   

                                         Description  
0  Fresh Air from WHYY, the Peabody Award-winning...  
1  Since its launch in 1997, The Moth has present...  
2  Design is everywhere in our lives, perhaps mos...  
3  The iFanboy.com Comic Book Podcast is a weekly...  
4  Jason Weiser tells stories from myths, legends...

In [55]:
podcast = data[['Name','Genre','Description']]
podcast.head()

Name       Genre  \
0                       Fresh Air        Arts   
1                        The Moth  Performing   
2                   99% Invisible      Design   
3  iFanboy.com Comic Book Podcast      Visual   
4               Myths and Legends  Literature   

                                         Description  
0  Fresh Air from WHYY, the Peabody Award-winning...  
1  Since its launch in 1997, The Moth has present...  
2  Design is everywhere in our lives, perhaps mos...  
3  The iFanboy.com Comic Book Podcast is a weekly...  
4  Jason Weiser tells stories from myths, legends...

In [56]:
podcast.shape

(13632, 3)

In [57]:
combine_features = data['Name'] + ' ' + data['Genre'] + ' ' + data['Description']

In [58]:
print(combine_features)

0        Fresh Air Arts Fresh Air from WHYY, the Peabod...
1        The Moth Performing Since its launch in 1997, ...
2        99% Invisible Design Design is everywhere in o...
3        iFanboy.com Comic Book Podcast Visual The iFan...
4        Myths and Legends Literature Jason Weiser tell...
                               ...                        
13627    Puromac Tech News Puromac es una conversación ...
13628    AVexcel Tech News AVexcel is your guide to the...
13629    Take a Network Break And Get The Latest Networ...
13630    AVexcel Tech News AVexcel is your guide to the...
13631    Take a Network Break And Get The Latest Networ...
Length: 13632, dtype: object


In [59]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combine_features)

In [60]:
similarity = cosine_similarity(feature_vectors)

In [61]:
print(similarity)

[[1.         0.03788201 0.06123121 ... 0.01265802 0.01258005 0.01265802]
 [0.03788201 1.         0.03762742 ... 0.04220054 0.01630242 0.04220054]
 [0.06123121 0.03762742 1.         ... 0.01621951 0.0209209  0.01621951]
 ...
 [0.01265802 0.04220054 0.01621951 ... 1.         0.08363158 1.        ]
 [0.01258005 0.01630242 0.0209209  ... 0.08363158 1.         0.08363158]
 [0.01265802 0.04220054 0.01621951 ... 1.         0.08363158 1.        ]]


In [62]:
import difflib
podcast_Name = str(input('Enter the name of your favorite podcast : '))
list_of_all_names = data['Name'].tolist()
find_close_match = difflib.get_close_matches(podcast_Name, list_of_all_names)
print(find_close_match)

['99% Invisible', 'Invisibilia']


In [63]:
close_match = find_close_match[0]
print(close_match)

99% Invisible


In [64]:
index_of_the_podcast_name = data[data['Name'] == close_match]['index'].values[0]
print(index_of_the_podcast_name)

2


In [65]:
similarity_score = list(enumerate(similarity[index_of_the_podcast_name]))

In [66]:
sorted_similar_podcast_name = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_podcast_name)

[(2, 1.0000000000000002), (49, 0.3574638597990968), (10541, 0.336698052007208), (139, 0.286537515875172), (10482, 0.28526263113149875), (6281, 0.27079003754320474), (5342, 0.2553137531771774), (10425, 0.24676330377316893), (10451, 0.23335618081717152), (10379, 0.2326886557636677), (249, 0.21843219313912948), (295, 0.2160815178590081), (10409, 0.21529121246007166), (364, 0.21328035770178946), (462, 0.20949220443333635), (269, 0.20711624787891472), (366, 0.19031985476800706), (416, 0.19027041731214042), (326, 0.187199632293044), (405, 0.18640753795588472), (2334, 0.18536493663246537), (380, 0.18438939691499318), (293, 0.1789808136685891), (255, 0.17662326356426092), (306, 0.17641250724979915), (5946, 0.1761314110860536), (393, 0.1760761820205066), (408, 0.1747900325263273), (430, 0.16901118574711052), (381, 0.16788416109510784), (38, 0.16773483391049968), (361, 0.1655171988172967), (292, 0.16421106520091333), (52, 0.1614289367712589), (300, 0.1609284691091835), (2355, 0.1590480867954934)

In [67]:
print('Podcast recommended for you : \n')

i = 1

for name in sorted_similar_podcast_name:
  index = name[0]
  title_from_index = data[data.index==index]['Name'].values[0]
  if (i<10):
    print(i, '.',title_from_index)
    i+=1

Podcast recommended for you : 

1 . 99% Invisible
2 . The Allusionist
3 . Millennial
4 . Design and Architecture
5 . Benjamen Walker's Theory of Everything
6 . The Heart
7 . What Trump Can Teach Us About Con Law
8 . The Mortified Podcast
9 . Radio Diaries


<h2 align='center'>| FINAL PODCAST RECOMMENDATION SYSTEM |</h2>

In [68]:
# podcast_Name = input(' Enter your favourite podcast name : ')

# list_of_all_names = data['Name'].tolist()

# find_close_match = difflib.get_close_matches(podcast_Name, list_of_all_names)

# close_match = find_close_match[0]

# index_of_the_podcast_name = data[data.Name == close_match]['index'].values[0]

# similarity_score = list(enumerate(similarity[index_of_the_podcast_name]))

# sorted_similar_podcast_name = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

# print('Podcast recommended for you : \n')

# i = 1

# for movie in sorted_similar_podcast_name:
#   index = movie[0]
#   title_from_index = data[data.index==index]['title'].values[0]
#   if (i<30):
#     print(i, '.',title_from_index)
#     i+=1